---

- name: remove GlusterFS PPA
  apt_repository:
    repo: "ppa:gluster/glusterfs-3.7"
    state: absent
  tags:
    - storage
    - gluster

- name: remove GlusterFS client
  apt:
    name: "glusterfs-client"
    state: absent
  tags:
    - storage
    - gluster

- name: Install NFS client
  apt:
    name: "nfs-common"
    state: present
  tags:
    - storage
    - efs

- name: Install mesos
  apt:
    name: mesos
    state: latest
  tags:
    - mesos

- name: Enable haproxy ppa
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.6"
    state: present
  tags:
    - haproxy
    - consul-template

- name: Install haproxy
  apt:
    name: "haproxy"
    state: present
  tags:
    - haproxy
    - consul-template
