---

- name: Ensure iptables rules are installed
  apt:
    name: "iptables-persistent"
    state: "present"
  tags:
    - metadata

- name: Add metadata proxy iptables rule
  shell: "iptables --append PREROUTING --destination 169.254.169.254 --protocol tcp --dport 80 --in-interface docker0 --jump DNAT --table nat --to-destination {{ ansible_default_ipv4['address'] }}:8000 --wait"
  become: yes
  tags:
    - metadata

- name: Add metadata proxy iptables rule
  iptables:
    in_interface: docker0
    chain: "INPUT"
    protocol: tcp
    destination_port: 80
    jump: DROP
    comment: "Drop other traffic"
  become: yes
  tags:
    - metadata

- name: Save iptables rules
  shell: "invoke-rc.d iptables-persistent save"
  become: yes

- name: Run docker for AWS metadata proxy
  docker_container:
    name: metadata_proxy
    image: "mozillaiam/metadataproxy:latest"
    restart_policy: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    exposed_ports:
      - 8000
  tags:
    - metadata
    - metadata_docker
